train:
  optimizer: Adam
  optimizer_args:
    lr: 0.01

  dataset:
    data: mnist
    mode: train


  dataloader:
    shuffle: True
    batch_size: 16
    num_workers: 8


  loss_fn: CrossEntropyLoss
  epochs: 10
  scheduler: None

val:
  dataset:
    data: mnist
    mode: valid
    preprocess: 123
